add_newline = true

format = """
[](blue)$directory[](blue) $git_branch
$character
"""

[directory]
style = "bold blue"
truncation_length = 3

[git_branch]
symbol = " "
style = "bold mauve"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](red)"

[aws]
disabled = true
[gcloud]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[docker_context]
disabled = true
