conky.config = {
    alignment = 'top_right',
    background = false,
    border_width = 0,
    cpu_avg_samples = 2,
    default_color = '#cdd6f4',
    color1 = '#89b4fa',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'UbuntuMono Nerd Font:size=10',
    gap_x = 30,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 300,
    maximum_width = 300,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

conky.text = [[
${color1}${font UbuntuMono Nerd Font:bold:size=11}SYSTEM ${hr 2}${color}
${font}IP:$alignr${addr wlo1}
HOST:$alignr$nodename
UPTIME:$alignr$uptime

${color1}${font UbuntuMono Nerd Font:bold:size=11}PROCESSORS ${hr 2}${color}
${font}${cpugraph 30,300 89b4fa cdd6f4}
CPU0: ${cpu cpu1}% ${alignr}${cpubar cpu1 8,200}
CPU1: ${cpu cpu2}% ${alignr}${cpubar cpu2 8,200}
CPU2: ${cpu cpu3}% ${alignr}${cpubar cpu3 8,200}
CPU3: ${cpu cpu4}% ${alignr}${cpubar cpu4 8,200}

${color1}${font UbuntuMono Nerd Font:bold:size=11}MEMORY ${hr 2}${color}
${font}RAM $alignc $mem / $memmax $alignr $memperc%
${membar 8,300}
SWAP $alignc $swap / $swapmax $alignr $swapperc%
${swapbar 8,300}

${color1}${font UbuntuMono Nerd Font:bold:size=11}STORAGE ${hr 2}${color}
${font}root $alignc ${fs_used /} / ${fs_size /} $alignr ${fs_used_perc /}%
${fs_bar 8,300 /}

${color1}${font UbuntuMono Nerd Font:bold:size=11}TOP PROCESSES ${hr 2}${color}
${font}${top name 1} $alignr ${top cpu 1}%
${top name 2} $alignr ${top cpu 2}%
${top name 3} $alignr ${top cpu 3}%
${top name 4} $alignr ${top cpu 4}%
${top name 5} $alignr ${top cpu 5}%

${color1}${font UbuntuMono Nerd Font:bold:size=11}NETWORK ${hr 2}${color}
${font}Download: ${downspeed wlo1} $alignr Total: ${totaldown wlo1}
${downspeedgraph wlo1 30,300 89b4fa cdd6f4}
Upload: ${upspeed wlo1} $alignr Total: ${totalup wlo1}
${upspeedgraph wlo1 30,300 89b4fa cdd6f4}
]]
